# version: '3'

# services:
#   database:
#     image: mysql:8.2
#     environment:
#       MYSQL_DATABASE: symfony_candidature
#       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#     ports:
#       - "8000:3306"
#     restart: always

#     volumes:
#       - db-data:/var/lib/mysql:rw

#   app:
#     image: bb8d6b15c325db4b51f523b244a026e64b846b1930ef46d48c03d44b695b3c0b
#     ports:
#       - "8080:80"
#     volumes:
#       - .:/var/www/html:rw

# volumes:
#   db-data:


version: "3.8"
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: apisymfony
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
   
    ports:
      - "3306:3306"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev

  www:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

networks:
  dev:
